### ISSUE TITLE
Export: Cannot click on markdown

### ISSUE THREAD

**Issue by rugk** [JohnMcLear/ep_markdown#15]
I can click on all other export options - except markdown. Even the cursor does not change when hovering over it.

**Comment by JohnMcLear** [comment]
Browser?

On 3 May 2016 22:59, rugk <notifications@github.com> wrote:

I can click on all other export options - except markdown. Even the cursor does not change when hovering over it.

**Comment by rugk** [comment]
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by JohnMcLear** [comment]
Works fine for me, please provide steps to replicate.

**Comment by rugk** [comment]
Well... difficult.

In the DOM view I at first see you put some inline style before the button. I think this is bad practise. Other plugins [including XMP export](https://github.com/stefanmintert/ep_xmlexport) seem to do it in another way. The additional `margin-left: -4` you're adding there also seems unnecessary (it is not used in the other export links).

But the issue just seems to be that there is no `href` attribut in the `a` tag. So obviously it cannot work.
When I manually access the export URL it works.

![export](https://cloud.githubusercontent.com/assets/11966684/15046195/cc129dbe-12de-11e6-8d88-3f2fdd059aae.png)

BTW I'm using [nginx as a proxy with proxy_rewrite from a subdirectory](https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#from-subdirectory-url).

Please reopen this issue. If you need further information, just ask.

**Comment by JohnMcLear** [comment]
href is being written fine for me..  try access it directly and see if you get the same problem.

**Comment by JohnMcLear** [comment]
https://github.com/JohnMcLear/ep_markdown/blob/master/static/js/main.js#L2 is probably the offending section, you will need to debug yourself to find out why it's b0rked for you

**Comment by rugk** [comment]
I found it. The JS was not loaded at all.
See my PR.

Can you please merge it and push a new version to nmp?

**Comment by JohnMcLear** [comment]
done
