### ISSUE TITLE
"html export" exports titles twice (etherpad 13)

### ISSUE THREAD

**Issue by agerodol** [JohnMcLear/ep_markdown#7]
I've just installed ep_markdown on a fresh etherpad 13 (using turnkey image).
everything seems alright, except that when I try an "html export", the resulting html file contains each title twice.
If I uninstall ep_markdown, just keeping ep_headings, titles are only exported once.

**Comment by JohnMcLear** [comment]
Resolved.  Tnx

**Comment by agerodol** [comment]
juste checked again, works nice now.
thanks,
Anne

**Comment by JohnMcLear** [comment]
Donations welcome on http://etherpad.org :)
