### ISSUE TITLE
is it possible to use ep_markdown with ep_headings2 ?

### ISSUE THREAD

**Issue by agerodol** [JohnMcLear/ep_markdown#8]
having observed a problem with html exports, I've decided to try ep_headings2.
so I uninstalled ep_headings and ep_markdown, installed ep_headings2 using npm.
and...
ep_headings was installed again.

I put this in the issues section, although maybe it's my mistake (I'm new to nodejs, and I don't know exactly how dependencies are managed)

**Comment by JohnMcLear** [comment]
Please read this: http://mclear.co.uk/2015/01/15/how-to-write-a-bug-report-for-dummies/

If you can replicate then feel free to re-open this issue.

**Comment by JohnMcLear** [comment]
It does appear ep_markdown thinks it depends on ep_headings..  not sure why!

**Comment by JohnMcLear** [comment]
I pushed a new version without the dep
